### ISSUE TITLE
Data metadata

### ISSUE THREAD

**Issue by fosrias** [ionwg/ion-doc#18]
@lhazlewood One thing you might want to think about for the future is the idea of a meta object containing a member that describes the data properties of an ion object. This would be really powerful from the standpoint of a self describing message. That could be a link to keep things light that could be transcluded or it could be an object with descriptions.

One reason you may want to think about this now is that how would be describing data would be a subset of the Form Member Types. So, you might want to think about this and how you could add this later and re-use concepts to describe form members to describe property members. 

This for example would allow you to have label suggestions to present that actual data values and for clients to have more complete knowledge of the message.

It would also differentiate this media-type from pretty much all the others and I don't think it would be hard to do.

Just passing that on.

**Comment by smizell** [comment]
Just a note, I did something like this for [Verbose](http://verbose.readthedocs.io/en/latest/specification.html#semantics) for adding semantic information. However, please note, this example is a tad—wait for it—verbose. Maybe there are some ideas there :)

**Comment by lhazlewood** [comment]
@fosrias and @smizell I think we're actually on the same page - great minds think alike ;)

The way I see it, the thing that describes the data properties of an object is... a form!

In other words, a form has field definitions, and each field has constraints.  Assuming the available constraint capabilities (i.e. form field attributes) are robust enough, there is no difference between this and what most of us think of as schema.  The only difference is conceptual - most people view schemas as fixed and mostly non-mutable, whereas forms are essentially the same thing but are perceived to be more dynamic.  This is why I think forms are better to 'hang your hat on' for a data interchange spec because it is less limiting and can handle more use cases than traditional schema concepts.

Maybe the only concrete difference I can think of is that a schema's fields do not have a `value` attribute, and form fields do?

The notion of schemas vs forms were at the forefront of every design decision I made when defining Ion's form concept, so I'm really happy to see that you guys clued in to that right away.

Does this mental model make sense to you? Or any other thoughts about how this might not work or be a good idea?

> This for example would allow you to have label suggestions to present that actual data values and for clients to have more complete knowledge of the message.

This is the purpose of the current form field `name`, `label and `placeholder` and `options` attributes - to allow a client the ability to discover all meaningful things about that particular field.  Are these concepts not sufficient for what you were thinking about?

**Comment by lhazlewood** [comment]
@fosrias or @smizell any thoughts about the above?

**Comment by lhazlewood** [comment]
@fosrias or @smizell I'm closing this as I believe Ion Forms satisfy all the conditions that you discuss above.  If this isn't the case, or you believe something is missing *please* re-open or create a new issue - I wouldn't want to miss out on any insight if you feel something is missing.  Thanks!
