### ISSUE TITLE
Address versioning the media-type

### ISSUE THREAD

**Issue by fosrias** [ionwg/ion-doc#7]
Semantic versioning? Will this change much? Constraints? 

Top-level meta tag only.

**Comment by lhazlewood** [comment]
Since this issue describes versioning the media type itself, I wonder if we can close this issue via the following:

`application/ion+json`

will always assume version 1 of the Ion spec.  This is semantically equivalent to:

`application/ion+json;v=1`

(`v` instead of `version` just because it is shorter - might as well save some bytes which actually matters when transferring billions of documents at scale).

We can do `application/ion+json;v=semver` where `semver` is a semantic version of a new spec after 1.0 has been finalized and registered w/ IANA.

We forego defining any `version` field in a `meta` object for now, as that would represent the resource itself, not the Ion version.  When this is discussed, things like schemas are relevant and should be resolved at that time (i.e. a resource version is inherently tied to the notion of a schema in some way, and schemas might be better left to other spec efforts).

Thoughts?

**Comment by fosrias** [comment]
Hm. Well, I don't think I would put resource versioning in the message body (ion object) itself, but use ETags or something for that. I can support the above. Just wondering whether having a `version` property in a top-level meta object should carry the same information for insurance purposes regarding the media type version. Adds a little extra complexity depending on where we allow meta objects to show up but frankly that may not matter and may be useful if some v=2 meta object expands some v=1 media type to have it in the meta object itself, as a possible edge case.

**Comment by lhazlewood** [comment]
There are 3 version concepts that I think people struggle with:

1.  Version of the media type itself.  As far as this particular issue is concerned, I think we can close the issue: the Ion media type version is assumed to be 1 unless a `v=semver` media type param exists.
2.  Version of the resource format or *schema*.  This is what most people struggle with I think.
3.  Version of the resource *instance* itself.  This is what ETags are for IMO.

I think #2 is what most people try to solve by representing in the media type declaration or a customer header, but I think we temporarily postpone that discussion and close this current issue.  Any objections?

**Comment by fosrias** [comment]
Well, I actually bounced this one off @mamund as in most of the specs he develops, he adds the version number into the data structure itself for insurance vs. the content-type or some external. If you think about your protocol independent argument of Ion in https://github.com/ionwg/ion-doc/issues/4, using content-type to define the version means that protocols that don't use that have to each define how to do versioning of the document structure.

Imagine sticking this on a queue or something and being able to know the version type. Not strongly opinionated here. Just trying to raise some issues for you to think about @lhazlewood.

**Comment by lhazlewood** [comment]
Good feedback - thanks @fosrias.  I think defining how the version is represented is only half the issue - the other half is how to request a resource that adheres to a particular format version, and how to do that is likely to be protocol specific.

In the same spirit as a meta `version` field, there could be a `schema` field, and schema version numbers are often embedded in the schema's IRI (e.g. like XML `xmlns` values or older Doctype declarations).  Then again, there is the issue of how to request a particular schema version, and I think this is protocol specific.

In any event, unless you guys object, I think we can close this issue and worry about how to represent (and query) for particular resource format versions when we tackle protocol specifics (e.g. An HTTP or REST 'profile' of Ion).  Any objections?

**Comment by fosrias** [comment]
@lhazlewood Fine with me.

**Comment by lhazlewood** [comment]
Closing this out.  I created #11 to track spec work related to other version concepts.
